x-env-file: &env_file
  - .env

name: yarr

services:
  yarr-backend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.backend
    container_name: yarr-backend
    image: yarr-backend:latest
    restart: unless-stopped
    env_file: *env_file

  yarr-frontend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.frontend
    container_name: yarr-frontend
    image: yarr-frontend:latest
    ports:
      - "7070:80"
    restart: unless-stopped
    depends_on:
      - yarr-backend
